services:
  backend:
    build:
      context: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - app-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      -"80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network: