name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build BE Docker image
        uses: docker build -t backend-test ./backend

      - name: Build FE Docker image
        uses: docker build -t frontend-test ./frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H buld.site >> ~/.ssh/known_hosts

      - name: SSH and deploy
        run: |
          ssh -i ~/.~/.ssh/id_ed25519 mdah@buld.site << 'EOF'
            cd aiqa6/
            git pull origin main
            docker compose -f dockercompose.yml up -d --build
          EOF